import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Image from "next/image";
import Header from "../../components/Header";
import Head from "next/head";
import Actor from "../../components/Actor";
import { bgWrap, bgText } from "./styles.module.css";
import moment from "moment";
function Movie({ movie, cast }) {
  const BASE_URL = "https://image.tmdb.org/t/p/original/";
  const BASE_URL_FACE = "https://image.tmdb.org/t/p/w138_and_h175_face/";
  let imageSrc = `${BASE_URL}${movie.backdrop_path}`;
  let posterSrc = `${BASE_URL}${movie.poster_path}`;
  let realeaseYear = moment(movie.release_date).format("YYYY");

  let link =
    "https://www.themoviedb.org/movie/338953-fantastic-beasts-the-secrets-of-dumbledore";
  let link2 = "https://www.youtube.com/watch?v=5UPdRF5xpVM";
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="flex p-7">
        <div>
          <Image
            layout="fixed"
            height={560}
            width={360}
            alt="thumbnail"
            src={posterSrc}
          />
        </div>

        <div className="flex flex-col px-4 mt-5 mb-5 ">
          <div className="text-4xl font-semibold mt-3">
            {movie.original_title} ({realeaseYear})
          </div>
          <div className="text-slate-400">{movie.tagline}</div>
          <div className="flex flex-row mt-3">
            <div className="mx-2">
              <div
                className="radial-progress text-warning ml-1"
                style={{ "--value": movie.vote_average * 10 }}
              >
                {`${movie.vote_average * 10}%`}
              </div>
            </div>

            <div className="self-center mx-2">{movie.release_date} </div>
            <div className="self-center mx-2"> {movie.runtime} mins</div>
          </div>
          <div className="mt-3">
            {movie.genres.map((genre) => (
              <div className="badge badge-outline mx-2" key={genre.id}>
                {genre.name}
              </div>
            ))}
          </div>
          <div className="mt-3">{movie.overview}</div>
        </div>
      </div>
      <div>
        <div></div>
        {/* <pre>{JSON.stringify(movie, null, 2)}</pre> */}
        <div className="flex flex-wrap justify-center">
          {cast.cast.slice(0, 9).map((element) => (
            <Actor key={element.id} actor={element} />
          ))}
        </div>
        sala
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const API_KEY = process.env.API_KEY;

  const movieID = context.query.id;
  const request = await fetch(
    `https://api.themoviedb.org/3/movie/${movieID}?api_key=${API_KEY}&language=en-US`
  ).then((res) => res.json());

  const imageRoute = `https://api.themoviedb.org/3/movie/${movieID}/credits?api_key=${API_KEY}&language=en-US`;
  const castRequest = await fetch(imageRoute).then((res) => res.json());
  return {
    props: {
      movie: request,
      cast: castRequest,
    },
  };
}

export default Movie;
