import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  // so the server will fetch the data and pass it as props to this component
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

// this gets executed before the Home component is sent to the client
// context includes details like the url that the user typed
export async function getServerSideProps(context) {
  const genre = context.query.genre;

  // genre is the genre of the movies we clicked on the navbar which is also a key to the requests , that way with each genre clicked it corresponds to a request

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    }, // will be passed to the page component as props
  };
}
